### ISSUE TITLE
Can we compare two different emails

### ISSUE THREAD

**Issue by sajeeshgit** [dunbarcyber/cyphondock#71] opened 2018-04-01 22:41 UTC
Hi team,

A quick question, can we compare two emails with the same subject but coming in a different time stamp. Need to compare few strings in the content of both the emails( of same subject ) and then generate an alert. Please let me know.

Thanks.

**Comment by chasepbrewer** [comment] 2018-04-05 18:46
Duplicate of dunbarcyber/cyphon#484

Closing here while we track the progress of that feature over in the other repository.

**Closed by chasepbrewer** 2018-04-05 18:46 UTC
Labels: duplicate
